freebsd_instance:
  image_family: freebsd-14-2
  cpu: 2
  memory: 2G

task:
  env:
    PERL_VERSION: "5.38"
  install_script:
    - sudo pkg install -y perl$PERL_VERSION
    - |
      export MYPERL=$( pkg info -l perl$PERL_VERSION | grep -m1 '/usr/local/bin/perl5[0-9.]\+$' )
      echo "MYPERL=$MYPERL" >> $CIRRUS_ENV
    - $MYPERL -V
    - cc -v
    - curl -L https://cpanmin.us | $MYPERL - --sudo App::cpanminus local::lib
  deps_script:
    - eval $( $MYPERL -Mlocal::lib=local )
    # Configure deps
    - $MYPERL -S cpanm -nq ExtUtils::MakeMaker Devel::CheckLib File::Which Inline::C
    # Deps
    - $MYPERL -S cpanm -nq --installdeps .
  build_script:
    - eval $( $MYPERL -Mlocal::lib=local )
    - make # -j $( sysctl -n hw.ncpu )
  test_script:
    - eval $( $MYPERL -Mlocal::lib=local )
    - make test
