#!/bin/sh

set -e

[ -x /usr/bin/update-menus ] && /usr/bin/update-menus

# work around potential dpkg breakage
#  if [ "$1" = "configure" ]; then
#        if [ -d /usr/doc -a ! -e /usr/doc/pdl \
#            -a -d /usr/share/doc/pdl ]; then
#                ln -sf ../share/doc/pdl /usr/doc/pdl
#        fi
#  fi

/usr/bin/perl /usr/lib/perl5/PDL/Doc/scantree.pl >/dev/null 2>&1
/usr/bin/perl /usr/lib/perl5/PDL/Doc/mkhtmldoc.pl >/dev/null 2>&1
