#!/bin/sh
# work around "fix" for potential dpkg breakage 
#  if [ \( "$1" = "upgrade" -o "$1" = "remove" \) \
#       -a -L /usr/doc/pdl ]; then
#        rm -f /usr/doc/pdl
#  fi

case "$1" in
	upgrade|remove)
		rm -rf /usr/lib/perl5/PDL/HtmlDocs
		rm -f  /usr/lib/perl5/PDL/pdldoc.db /usr/lib/perl5/PDL/Index.pod
		;;
esac
